name: Publish Extensions

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  CI: true
  AZURE_REGISTRY_NAME: bicepextgithub

jobs:
  deploy-acr:
    name: Deploy ACR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
          submodules: true

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: Deploy
        run: |
          az deployment group create \
            --resource-group ${{ env.AZURE_REGISTRY_NAME }} \
            --parameters ./infra/main.bicepparam

  publish-extension:
    needs: deploy-acr
    name: Publish Extension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
          submodules: true

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: Intall CLI
        run: az bicep install --version v0.30.23
      
      - name: Run nbgv
        id: nbgv
        uses: dotnet/nbgv@v0.4.2
        
      - name: Publish Extension
        run: |
          target="br:${{ env.AZURE_REGISTRY_NAME }}.azurecr.io/extensions/github:${{ steps.nbgv.outputs.SimpleVersion }}"
          bash scripts/publish.sh $target

          echo "Published extension \`$target\`." >> $GITHUB_STEP_SUMMARY